controller_list:
  - name: fake_explorer_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_paw_controller
    joints:
      - joint4
      - joint5
      - joint6